version: '3.4'
services:
  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - joomla
    ports:
      - '8080:80'
    volumes:
      - ${PWD}/nginx:/etc/nginx/conf.d:ro
      - ${PWD}/joomla:/var/www/html:ro

  joomla:
    image: joomla:3.8.0-fpm-php7
    depends_on:
      - memcached
      - mariadb
    environment:
      JOOMLA_DB_HOST: mariadb
      JOOMLA_DB_NAME: joomla
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: changeme
    volumes:
      - ${PWD}/joomla:/var/www/html

  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: changeme
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql

  memcached:
    image: memcached:1.5.3-alpine
