version: '3.4'
services:
  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - postgresql
    ports:
      - '8080:80'
    volumes:
      - ${PWD}/nginx:/etc/nginx/conf.d
      - ${PWD}/mantisbt/mantisbt:/var/www/html

  mantisbt:
    build: mantisbt
    restart: always
    depends_on:
      - postgresql
    volumes:
      - ${PWD}/mantisbt/mantisbt:/var/www/html

  postgresql:
    image: postgres:10.0
    environment:
      POSTGRES_DB: mantisbt
      POSTGRES_USER: mantisbt
      POSTGRES_PASSWORD: changeme
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ${PWD}/postgres/data:/var/lib/postgresql/data

